# Generated by Django 3.2.4 on 2022-03-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tasks",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_id",
                    models.IntegerField(db_index=True, verbose_name="标准运维任务ID"),
                ),
                ("bk_biz_id", models.IntegerField(db_index=True, verbose_name="业务id")),
                (
                    "template_id",
                    models.IntegerField(db_index=True, verbose_name="标准运维模板id"),
                ),
                ("task_name", models.CharField(max_length=50, verbose_name="任务名")),
                (
                    "status",
                    models.CharField(
                        default="CREATED", max_length=20, verbose_name="任务状态"
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        default="admin", max_length=32, verbose_name="创建者"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "params",
                    models.JSONField(blank=True, null=True, verbose_name="标准运维全局参数"),
                ),
                (
                    "task_url",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="task链接地址"
                    ),
                ),
            ],
            options={
                "verbose_name": "标准运维任务列表",
                "verbose_name_plural": "标准运维任务列表",
            },
        ),
    ]
